---
title: "Spotify Analysis"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    logo: 
      src: "github_logo.png"
      href: "https://github.com/Quinveee/Computational-Musicology"
    css: style.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidytext)
library(tidyverse)
library(spotifyr)
library(flexdashboard)
library(plotly)

corpus <- get_playlist_audio_features("", "75LhP6wXfee0eYHuW28nkw")
corpus |>
  summarise(
    mean_speechiness = mean(speechiness),
    mean_acousticness = mean(acousticness),
    mean_liveness = mean(liveness),
    sd_speechiness = sd(speechiness),
    sd_acousticness = sd(acousticness),
    sd_liveness = sd(liveness),
    median_speechiness = median(speechiness),
    median_acousticness = median(acousticness),
    median_liveness = median(liveness),
    mad_speechiness = mad(speechiness),
    mad_acousticness = mad(acousticness),
    mad_liveness = mad(liveness)
  )
```

Corpus
=====================================

Column {data-width=350}
-------------------------------------

### Analysis of my Personal Spotify Library

#### Corpus Description

The corpus for this musical analysis consists of a collection of albums (see Appendix) that I chose based on my personal interest. I chose albums specifically, as it is the form in which I consume most of my music, but it will also ensure that the overlap in musical genres is more consistent between songs. This does however mean that the analysis will focus more on the difference between the albums as opposed to differences between individual songs. As for the corpus, it consists of a variety of genres including rock, pop, post-rock, ambient, shoegaze, neo-psychedelia, hip-hop. At first glance it might seem as if there is little overlap between the album’s genres, however, most can be categorized in either rock, ambient, pop, or hip-hop. Though there are some album’s that can be considered atypical for these categories, for example LONG SEASON by the Fishmans. This album consists of a single 35-minute song and incorporates a variety of genres into one. Another example is REGRET WHEN IT WAS LOST by death’s dynamic shroud which at points blurs the line between surrealism and music. Or F# A# ∞ by Godspeed You! Black Emperor, an album containing multiple monologues throughout the song creating an eerie vibe. I chose to incorporate these albums not only because they are some of my personal favorites but also for their uniqueness, which should hopefully lead to a more interesting analysis. The corpus contains many more such examples, which I will cover further in the analysis. However, most of the corpus consists of more typical genre representative albums, for example the albums made by; Radiohead, No Party For Coa Dong, tricot, Pink Floyd, Polyphia and Panchiko, are more typical to rock. So, all in all, the corpus consists of a combination of typical and atypical albums which should lead to an interesting analysis of the distinctions an overlap between genres and individual albums/songs.

#### Plot 1

Plot 1 shows a comparrison of the liveness, acousticness and the speechness of each individual song. What is interesting about the plot is that there appears to be verry little acousticness and speechness. This is relativally odd as many of the songs should contain speech, furthermore, the acousticness seems rather low, possebly due to the amount of ambient music, but still apears low as there are manny rock albums. The liveliness on the other hand seems all over the place, likely due to the fast differences in genres.

#### Plot 2

Plot 2 shows the mean energy levels of all albums in decending order. What is interesting about this plot is that the albums seems to contain nearly the entire range of the energy spectrum, all the way from A I A: Alien Observer at a level of around 0.13 to World is Yours at almost 1, with an overall mean of around 0.6.


Column {data-width=650}
-------------------------------------

### Plot A

```{r, echo=FALSE}
multi_plot_1 <- ggplot(corpus, aes(x = liveness, acousticness, color = speechiness, size = speechiness)) + 
  geom_point() + 
  geom_jitter(alpha = 0.5, width = 0.1) +
  theme_classic() + 
  scale_color_viridis_c() + 
  guides(size = "none") +
  labs(x = "Acousticness",
       y = "Liveness",
       title = "Comparison of Liveness, Acousticness and Speechness",
       subtitle = "The plot consists of the liveness, acousticness and speechness of all individual songs"
  ) + 
  theme(
    legend.position = "Bottom"
  )

ggplotly(multi_plot_1)
```


### Plot B

```{r, echo=FALSE}
corpus_energy <- corpus %>% 
  group_by(track.album.name) %>%
  summarize(album_energy=mean(energy))

global_mean <- mean(corpus$energy)

energy_plot_1 <- ggplot(corpus_energy, aes(x = album_energy, y = reorder(track.album.name, album_energy), color = album_energy)) +
  geom_point(size = 3) +
  geom_vline(xintercept = global_mean, color = "grey40", linetype = 3) +
  geom_segment(aes(xend = 0, yend = track.album.name), size = 2) + 
  theme_classic() +
  theme(legend.position = 'none') +
  labs(x = "Album's Mean Energy",
       y = "Album",
       title = "Albums ranked on their mean energy level") + 
  annotate(
    "text",
    x = global_mean + 0.06, y = 8,
    label = "Global\nmean",
    vjust = 1, size = 3, color = "grey40"
  ) +
  theme(
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.subtitle = element_text(size = 9)
  )
  

ggplotly(energy_plot_1)

```


Analysis
=====================================



Findings
=====================================


